shopapp.webui/Models/ProductDetailModel.cs
using System.Collections.Generic;
using shopapp.entity;

namespace shopapp.webui.Models
{
    public class ProductDetailModel
    {
        public Product Product { get; set; }
        public List<Category> Categories { get; set; }
    }
}

shopapp.webui/Models/ProductListViewModel.cs
using System;
using System.Collections.Generic;
using shopapp.entity;

namespace shopapp.webui.Models
{
    public class PageInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }
        public string CurrentCategory { get; set; }

        public int TotalPages()
        {
             return (int)Math.Ceiling((decimal)TotalItems/ItemsPerPage);
        }
    }

    public class ProductListViewModel
    {
        public PageInfo PageInfo { get; set; }
        public List<Product> Products { get; set; }
    }
}

shopapp.webui/Models/ProductModel.cs
using System.ComponentModel.DataAnnotations;

namespace shopapp.webui.Models
{
    public class ProductModel
    {
        public int ProductId { get; set; }  
        [Display(Name="Name",Prompt="Enter product name")]
        public string Name { get; set; }       
        public string Url { get; set; }       
        public double? Price { get; set; } 
        public string Description { get; set; }         
        public string ImageUrl { get; set; }
        public bool IsApproved { get; set; }
        public bool IsHome { get; set; }
    }//burada ve viewde istediğin gibi oynarsın en sonda gönderirsin zaten controllerda bakarsan tüm değişiklik yapılmış modee gitmiş ve product.csy atılmış şekilde görürsün.
}

shopapp.webui/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using shopapp.business.Abstract;
using shopapp.entity;
using shopapp.webui.Models;

namespace shopapp.webui.Controllers
{
    public class AdminController:Controller
    {
        private IProductService _productService;
        public AdminController(IProductService productService)
        {
            this._productService=productService;
        }

        public IActionResult ProductList()
        {
            return View(new ProductListViewModel()
            {
                Products= _productService.GetAll(),//ana yerden efcoregenericten geliyor

            });
        }

        [HttpGet]
        public IActionResult CreateProduct()
        {//formu çağırdığım an bura get gelir. Gönderdiğim an postla gider oda aşağıda
            return View();            
        }
        [HttpPost]
        public IActionResult CreateProduct(ProductModel model)
        {//formu çağırdığım an bura get gelir. Gönderdiğim an postla gider
          var entity = new Product
          {
              Name=model.Name,
              Url=model.Url,
              Price=model.Price,
              Description=model.Description,
              ImageUrl=model.ImageUrl,
          };
          
           _productService.Create(entity);
           return RedirectToAction("ProductList");//postlayınca productlist sayfası gelsin
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if(id==null)
            {
                return NotFound();
            }
            var entity=_productService.GetById((int)id);
             if(entity==null)
            {
                return NotFound();
            }
            var model=new ProductModel()
            {
                ProductId=entity.ProductId,
                Name=entity.Name,
                Url=entity.Url,
                Price=entity.Price,
                ImageUrl=entity.ImageUrl,
                Description=entity.Description
            };
            return View(model);            
        }

        [HttpPost]
        public IActionResult Edit(ProductModel model)
        {
            var entity=_productService.GetById(model.ProductId);//modelin içindekini alıyoki kullanıcı girmesin
            if(entity==null)
            {
                return NotFound();
            }
            entity.Name=model.Name;
            entity.Price=model.Price;
            entity.Url=model.Url;
            entity.ImageUrl=model.ImageUrl;
            entity.Description=model.Description;
            _productService.Update(entity);
            return RedirectToAction("ProductList");         
        }
        
        [HttpPost]
        public IActionResult DeleteProduct(int productId)
        {
            var entity=_productService.GetById(productId);
            if(entity!=null)
            {
                _productService.Delete(entity);
            }
            return RedirectToAction("ProductList");         
        }


    }
}

shopapp.webui/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using shopapp.business.Abstract;
using shopapp.data.Abstract;
using shopapp.webui.Models;

namespace shopapp.webui.Controllers
{
    // localhost:5000/home
    public class HomeController:Controller
    {      
        private IProductService _productService;
        public HomeController(IProductService productService)
        {
            this._productService=productService;
        }
        
        public IActionResult Index()
        {
            var productViewModel = new ProductListViewModel()
            {
                Products = _productService.GetHomePageProducts()
            };

            return View(productViewModel);
        }

        public IActionResult About()
        {
            return View();
        }

         public IActionResult Contact()
        {
            return View("MyView");
        }
    }
}

shopapp.webui/Controllers/ShopController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using shopapp.business.Abstract;
using shopapp.entity;
using shopapp.webui.Models;

namespace shopapp.webui.Controllers
{
    public class ShopController:Controller
    {
        private IProductService _productService;
        public ShopController(IProductService productService)
        {
            this._productService=productService;
        }

        // localhost/products/telefon?page=1
        public IActionResult List(string category,int page=1)
        {
            const int pageSize=2;
            var productViewModel = new ProductListViewModel()
            {
                PageInfo = new PageInfo()
                {
                    TotalItems = _productService.GetCountByCategory(category),
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    CurrentCategory = category
                },
                Products = _productService.GetProductsByCategory(category,page,pageSize)
            };

            return View(productViewModel);
        }

        public IActionResult Details(string url)
        {
            if (url==null)
            {
                return NotFound();
            }
            Product product = _productService.GetProductDetails(url);

            if(product==null)
            {
                return NotFound();
            }
            return View(new ProductDetailModel{
                Product = product,
                Categories = product.ProductCategories.Select(i=>i.Category).ToList()
            });
        }

        public IActionResult Search(string q)
        {
            var productViewModel = new ProductListViewModel()
            {
                Products = _productService.GetSearchResult(q)
            };

            return View(productViewModel);
        }
    }
}

shopapp.webui/ViewComponents/CategoriesViewComponent.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using shopapp.business.Abstract;

namespace shopapp.webui.ViewComponents
{
    public class CategoriesViewComponent:ViewComponent
    {
        private ICategoryService _categoryService;
        public CategoriesViewComponent(ICategoryService categoryService)
        {
            this._categoryService=categoryService;
        }
        public IViewComponentResult Invoke()
        {
            if (RouteData.Values["category"]!=null)
                ViewBag.SelectedCategory = RouteData?.Values["category"];
                
            return View(_categoryService.GetAll());
        }
    }
}

shopapp.webui/Views/Admin/CreateProduct.cshtml
@model ProductModel //dto objeleri denir
<h1 class="h3">Create Product</h1>
<hr>

<div class="row">
   <div class="col-md-8">
<form asp-controller="Admin" asp-action="CreateProduct" method="Post">

        <div class="form-group row">
            <label asp-for="Name" class="col-sm-2 col-form-label">Name</label>
            <div class="col-sm-10">
            <input class="form-control" asp-for="Name">
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Url" class="col-sm-2 col-form-label">Url</label>
            <div class="col-sm-10">
            <input class="form-control" asp-for="Url">
            </div>
        </div>

       @* <div class="form-group row">
            <label class="col-sm-2 col-form-label">Url</label>
            <div class="col-sm-10">
            <input type="text" class="form-control" id="Url" name="Url"> 
            idyi js tarayıcı tarafında yaptığım işlemler için kullanırım. Name kısmını ise vtde yaptığım.
            bizim tag helperlerimiz var yani her divde id name yazmak yerine onları kullanabilirim çünkü buradaki id url ye verdiğim isim vtdekiyle aynı olmak zorunda belki yanlış falan yazarım diye ben tag helper kullanıcam bunun için yukarıya model eklemem lazım.
            şimdi ben id ve nameleri sileceğim
            tagleri nasıl kullanacağız asp-for="Url" bu şekilde kullanıyorum  modelde string bilgi tanımlıyosan text yazmana bile gerek yok onları bile silelim
            asp-for ları labelede verirsek oranında isimleri otomatik değişir 
            </div>
        </div>*@

        <div class="form-group row">
            <label asp-for="Description" class="col-sm-2 col-form-label">Description</label>
            <div class="col-sm-10">
            <textarea class="form-control" asp-for="Description"></textarea>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="ImageUrl" class="col-sm-2 col-form-label">ImageUrl</label>
            <div class="col-sm-10">
            <input class="form-control" asp-for="ImageUrl">
            </div>
        </div>
        
        <div class="form-group row">
            <label asp-for="Price" class="col-sm-2 col-form-label">Price</label>
            <div class="col-sm-10">
            <input class="form-control" asp-for="Price">
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-10 offset-sm-2">
                <button type="submit" class="btn btn-primary" >Gönder</button>
            </div>
        </div>



</form>

</div>
  </div>

shopapp.webui/Views/Admin/Edit.cshtml
@model ProductModel //dto objeleri denir
<h1 class="h3">Edit Product</h1>
<hr>

<div class="row">
   <div class="col-md-8">
<form asp-controller="Admin" asp-action="Edit" method="POST">

        <input type="hidden" name="ProductId" value="@Model.ProductId">

        <div class="form-group row">
            <label asp-for="Name" class="col-sm-2 col-form-label">Name</label>
            <div class="col-sm-10">
            <input class="form-control" asp-for="Name">
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Url" class="col-sm-2 col-form-label">Url</label>
            <div class="col-sm-10">
            <input class="form-control" asp-for="Url">
            </div>
        </div>

       @* <div class="form-group row">
            <label class="col-sm-2 col-form-label">Url</label>
            <div class="col-sm-10">
            <input type="text" class="form-control" id="Url" name="Url"> 
            idyi js tarayıcı tarafında yaptığım işlemler için kullanırım. Name kısmını ise vtde yaptığım.
            bizim tag helperlerimiz var yani her divde id name yazmak yerine onları kullanabilirim çünkü buradaki id url ye verdiğim isim vtdekiyle aynı olmak zorunda belki yanlış falan yazarım diye ben tag helper kullanıcam bunun için yukarıya model eklemem lazım.
            şimdi ben id ve nameleri sileceğim
            tagleri nasıl kullanacağız asp-for="Url" bu şekilde kullanıyorum  modelde string bilgi tanımlıyosan text yazmana bile gerek yok onları bile silelim
            asp-for ları labelede verirsek oranında isimleri otomatik değişir 
            </div>
        </div>*@

        <div class="form-group row">
            <label asp-for="Description" class="col-sm-2 col-form-label">Description</label>
            <div class="col-sm-10">
            <textarea class="form-control" asp-for="Description"></textarea>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="ImageUrl" class="col-sm-2 col-form-label">ImageUrl</label>
            <div class="col-sm-10">
            <input class="form-control" asp-for="ImageUrl">
            </div>
        </div>
        
        <div class="form-group row">
            <label asp-for="Price" class="col-sm-2 col-form-label">Price</label>
            <div class="col-sm-10">
            <input class="form-control" asp-for="Price">
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-10 offset-sm-2">
                <button type="submit" class="btn btn-primary" >Gönder</button>
            </div>
        </div>



</form>

</div>
  </div>

shopapp.webui/Views/Admin/ProductList.cshtml
@model ProductListViewModel

<div class="row">
    <div class="col-md-12">
        <h1>Admin Products</h1>
        <hr>
        <table class="table table-bordered">
          <thead>
              <td style="width:50px">Id</td>
              <td style="width:150px">Img</td>
              <td style="width:250px">Name</td>
              <td style="width:50px">Price</td>
              <td style="width:20px">AnaSayfa</td>
              <td style="width:20px">Onaylı</td>
              <td style="width:50px">Fiyat</td>
              <td style="width:50px">Erişim</td>

          </thead>
          <tbody>
           @if(Model.Products.Count>0)
           {
             @foreach (var item in Model.Products)//her bir eleman item içinde saklansın ve yapımız her gelen ürün için tr oluşsun
              {
                  <tr>
                    <td >@item.ProductId</td>
                    <td ><img src="~/img/@item.ImageUrl" width="80"></td>
                    <td >@item.Name</td>
                    <td >@item.Price</td>
                    <td>
                      @if(item.IsHome)
                      {
                        <i class="fas fa-check-circle"></i>
                      }
                      else
                      {
                        <i class="fas fa-times-circle"></i>
                      }
                    </td>
                    <td>
                      @if(item.IsApproved)
                      {
                        <i class="fas fa-check-circle"></i>
                      }
                      else
                      {
                        <i class="fas fa-times-circle"></i>
                      }

                    </td>
                    <td >@item.Price</td>
                  <td>
                      <a class="btn btn-primary btn-sm mr-2" href="/admin/products/@item.ProductId">Edit</a> @*admin altındaki pructsu göstersin eğer id gelirse bu butona detay sayfasına gitsin*@
                     <form action="/admin/deleteproduct" method="post" style="display: inline;">
                     <input type="hidden" name="ProductId" value="@item.ProductId">
                     <button type="submit" class="btn btn-danger btn-sm mr-2">Delete</button>
                     </form>
                  </td>
              </tr>
              }
           }
           else
           {
             <div class="alert alert-warning">
                 <h3>No Products</h3>
             </div>
           }
          </tbody>
        </table>
    </div>
</div>

shopapp.webui/Views/Home/About.cshtml
about

shopapp.webui/Views/Home/Index.cshtml
@model ProductListViewModel

<partial name="_header">

<div class="row">
    <div class="col-md-3">
        @await Component.InvokeAsync("Categories")
        <partial name="_search">
    </div>
    <div class="col-md-9">
        <div class="row">                  
            @foreach (var product in Model.Products)
            {    
                <div class="col-md-4">
                    @await Html.PartialAsync("_product", product)   
                </div>       
            }           
        </div>
    </div>
</div>



@section Scripts
{
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
}

shopapp.webui/Views/Home/MyView.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    home/contact
</body>
</html>

shopapp.webui/Views/Product/Create.cshtml
@model Product

<form method="POST">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label for="Name">Name</label>
        <input asp-for="Name" value="@Model.Name" class="form-control">  
        <span asp-validation-for="Name" class="text-danger"></span>  
    </div>
    <div class="form-group">
        <label for="Price">Price</label>
        <input asp-for="Price" value="@Model.Price" class="form-control">
         <span asp-validation-for="Price" class="text-danger"></span>  
    </div>
    <div class="form-group">
        <label for="Description">Description</label>
        <textarea asp-for="Description" value="@Model.Description" class="form-control"></textarea>
         <span asp-validation-for="Description" class="text-danger"></span>  
    </div>
    <div class="form-group">
        <label for="ImageUrl">ImageUrl</label>
        <input asp-for="ImageUrl" value="@Model.ImageUrl" class="form-control">
         <span asp-validation-for="ImageUrl" class="text-danger"></span>  
    </div>
    @* <div class="form-group">
        <label for="CategoryId">CategoryId</label>
        <select asp-for="CategoryId" asp-items="@ViewBag.Categories" class="form-control">
            <option selected disabled>Seçiniz</option>
        </select>
        <span asp-validation-for="CategoryId" class="text-danger"></span>  
    </div> *@
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

shopapp.webui/Views/Product/Details.cshtml
@model Product

@section Categories
{
    @await Component.InvokeAsync("Categories")
}

<div class="card mb-3">
    <div class="card-body">
        <div class="row no-gutters">
            <div class="col-md-3">
                <img src="~/img/@Model.ImageUrl" class="card-img">
            </div>
            <div class="col-md-9">
                
                    <h5 class="card-title">@Model.Name</h5>
                    <p class="card-text">@Model.Description</p>
                    <p class="card-text">
                        <small class="text-muted">3 days ago</small>
                    </p>
            
            </div>
        </div>
    </div>
</div>

shopapp.webui/Views/Product/Edit.cshtml
@model Product

<form method="POST">
    <input type="hidden" name="ProductId" value="@Model.ProductId"/>
    <div class="form-group">
        <label for="Name">Name</label>
        <input asp-for="Name" value="@Model.Name" class="form-control">
    </div>
    <div class="form-group">
        <label for="Price">Price</label>
        <input asp-for="Price" value="@Model.Price" class="form-control">
    </div>
    <div class="form-group">
        <label for="Description">Description</label>
        <textarea asp-for="Description" value="@Model.Description" class="form-control"></textarea>
    </div>
    <div class="form-group">
        <label for="ImageUrl">ImageUrl</label>
        <input asp-for="ImageUrl" value="@Model.ImageUrl" class="form-control">
    </div>
    @* <div class="form-group">
        <label for="CategoryId">CategoryId</label>
        <select asp-for="CategoryId" asp-items="@ViewBag.Categories" class="form-control">
            <option selected disabled>Seçiniz</option>
        </select>
    </div> *@
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

shopapp.webui/Views/Product/Index.cshtml
@section Categories
{
    @await Component.InvokeAsync("Categories")
}


product index

shopapp.webui/Views/Product/List.cshtml
@model ProductListViewModel


@{
    var popularClass = Model.Products.Count>2? "popular":"";
    var products = Model.Products;
}

@section Categories
{
    @await Component.InvokeAsync("Categories")
}

@if(products.Count == 0)
{
    @await Html.PartialAsync("_noproduct")
}
else
{
    <div class="row">                  
        @foreach (var product in products)
        {    
            <div class="col-md-4">
                @await Html.PartialAsync("_product", product)   
        </div>       
        }   
    </div>
}

shopapp.webui/Views/Shared/Components/Categories/Default.cshtml
@model List<Category>

 <div class="list-group">
    <a href="/products" class="list-group-item list-group-item-action">Tüm Kategoriler</a>

    @foreach (var item in Model)
    {
        <a asp-controller="Shop" 
        asp-action="List" 
        asp-route-category="@item.Url" 
        class="list-group-item list-group-item-action @(ViewBag.SelectedCategory == item.Url?"active":"")">
            @item.Name
        </a>
    }
</div>   

shopapp.webui/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" >
    <link rel="stylesheet" href="/modules/bootstrap/dist/css/bootstrap.min.css" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/style.css">
    <title>Shopapp</title>
</head>
<body>

    @await Html.PartialAsync("_navbar")          

    <main class="my-3">
        <div class="container">            
                    @RenderBody()            
        </div>
    </main>

    <footer class="py-5 bg-dark text-white text-center">
        Shop App
    </footer>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    @RenderSection("Scripts",false)
</body>
</html>

shopapp.webui/Views/Shared/_categories.cshtml
 @model List<Category>
 
 <div class="list-group">
    @foreach (var category in Model)
    {
        <a href="#" class="list-group-item list-group-item-action">@category.Name</a>
    }
</div>   

shopapp.webui/Views/Shared/_header.cshtml
 <header>
        <div class="jumbotron jumbotron-fluid">
            <div class="container">
                <h1 class="display-4">Shop App</h1>
                <p class="lead">Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque id, eum explicabo sed est hic corrupti et impedit, quasi quis alias, qui provident natus enim tempore? Nesciunt repellendus debitis minus!</p>
            </div>
        </div>
    </header>

shopapp.webui/Views/Shared/_navbar.cshtml
  <div class="navbar bg-danger navbar-dark navbar-expand-sm">
        <div class="container">
            <a href="/" class="navbar-brand">Shopapp</a>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a href="/products" class="nav-link">Products</a>
                </li>
                 <li class="nav-item">
                    <a href="" class="nav-link">Cart</a>
                </li>
                  <li class="nav-item">
                    <a href="" class="nav-link">Orders</a>
                </li>
                <li class="nav-item">
                    <a asp-controller="admin" asp-action="createproduct" class="nav-link">Add Product</a>
                </li>
                <li class="nav-item">
                    <a href="/admin/products" class="nav-link">Admin Products</a>
                </li>
            </ul>
        </div>
    </div>

shopapp.webui/Views/Shared/_noproduct.cshtml
 <div class="row">
                        <div class="col-md-12">
                            <div class="alert alert-danger">
                                Ürün yok    
                            </div>
                        </div>
                    </div>

shopapp.webui/Views/Shared/_product.cshtml
@model Product

<div class="card mb-2">
    <img class="card-img-top" src="~/img/@Model.ImageUrl" alt="">
    <div class="card-body">
        <h5 class="card-title">@Model.Name</h5>
        <small class="text-muted">
            <i class="fas fa-lira-sign"></i>@Model.Price
        </small>
    </div>
    <div class="card-footer text-center">
        <a asp-controller="shop" asp-action="Details" asp-route-url="@Model.Url" class="btn btn-primary btn-sm">Details</a>
        <a asp-controller="shop" asp-action="addtocart" asp-route-id="@Model.ProductId" class="btn btn-primary btn-sm">Add to Cart</a>
    </div>
</div>   

shopapp.webui/Views/Shared/_search.cshtml
  <div class="card mt-3">
      <div class="card-header">
          <h5>Search</h5>
      </div>
      <div class="card-body">
            <form action="/search">
                <div class="form-group">
                    <input name="q" type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-danger btn-sm btn-block">Ara</button>
            </form>
      </div>
  </div>
  
  

shopapp.webui/Views/Shop/Details.cshtml
@model ProductDetailModel

<div class="row">
    <div class="col-md-3">
        <img src="~/img/@Model.Product.ImageUrl" class="img-fluid">
    </div>
    <div class="col-md-9">                
            <h1 class="mb-3">@Model.Product.Name</h5> <hr>

            @foreach (var item in Model.Categories)
            {
                <a asp-controller="shop" asp-action="list" asp-route-category="@item.Url" class="btn btn-link p-0 mb-3">@item.Name</a> 
            }                          
            
            <div class="mb-3">
                <h4 class="text-primary mb-3">
                    <i class="fas fa-lira-sign"></i>@Model.Product.Price
                </h4>
                <button type="submit" class="btn btn-primary btn-lg">Add To Cart</button>
            </h6>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <p class="p-3">@Model.Product.Description</p>
    </div>
</div>

shopapp.webui/Views/Shop/List.cshtml
@model ProductListViewModel


<div class="row">
    <div class="col-md-3">
        @await Component.InvokeAsync("Categories")
    </div>
    <div class="col-md-9">
        <div class="row">                  
            @foreach (var product in Model.Products)
            {    
                <div class="col-md-4">
                    @await Html.PartialAsync("_product", product)   
                </div>       
            }           
        </div>

        <div class="row">
            <div class="col">
                <nav aria-label="Page navigation example">
                    <ul class="pagination">

                        @for (int i = 0; i < Model.PageInfo.TotalPages(); i++)
                        {
                            @if(String.IsNullOrEmpty(Model.PageInfo.CurrentCategory))
                            {
                                <li class="page-item @(Model.PageInfo.CurrentPage==i+1?"active":"")">
                                    <a class="page-link" href="/products?page=@(i+1)">
                                        @(i+1)
                                    </a>
                                </li>  
                            }
                            else
                            {
                                <li class="page-item @(Model.PageInfo.CurrentPage==i+1?"active":"")">
                                    <a class="page-link" href="/products/@Model.PageInfo.CurrentCategory?page=@(i+1)">
                                        @(i+1)
                                    </a>
                                </li> 
                            }

                                                   
                        }

                      
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</div>



@section Scripts
{
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
}

shopapp.webui/Views/Shop/Search.cshtml
@model ProductListViewModel

<div class="row">
    <div class="col-md-3">
        @await Component.InvokeAsync("Categories")
    </div>
    <div class="col-md-9">
        <div class="row">                  
            @foreach (var product in Model.Products)
            {    
                <div class="col-md-4">
                    @await Html.PartialAsync("_product", product)   
                </div>       
            }           
        </div>
    
    </div>
</div>



@section Scripts
{
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
}